# MultiQ Configuration File

# QPU Settings
entanglement_height: 12
qpu_width: 60
qpu_height: 50
zone_separation: 10
entanglement_site_separation: [12, 10]
storage_site_separation: [3, 3]
aod_minimum_separation: 2

# timing in us (microseconds)
time_rydberg: 0.36
time_atom_transfer: 15
time_1qGate: 0.625
r1q_time: 12.0

# Planner Settings
# weights for layout planning
util_weight: 0 # We dont use this one, we simply do (1 - perf_weight)
perf_weight: 1
zone_centering: [1,1] # Defines the centering of the entanglement and storage zones,
                      # 1:1 means the zone overlaps on each side are equal,
                      # 1:2 would push the smaller zone to the left

# lookahead for splitting circuit into parallel layers
layer_split_window: 10

# Circuit SA Scheduler
perf_weight_selector: 0.9 # Performance weight for scheduling
util_weight_selector: 0.1 # Utilization weight for scheduling
initial_temperature: 250.0 # Initial temperature for simulated annealing
cooling_rate: 0.8 # Cooling factor for simulated annealing
final_temperature: 0.5 # Final temperature for simulated annealing
max_iterations_per_temp: 10 # Number of iterations per temperature in simulated annealing
max_iterations: 1000 # Maximum number of iterations for the scheduler

# file path for temporary generation of architecture files
tmp_arch_file: "zac_config/tmp_architecture.json"

# Animation Settings
arch_padding: 0 # Padding around individual layouts

# Placement Settings
dynamic_placement: true
trivial_placement: false
storage_zone_rows: null
use_window: true
window_size: 1000
l2: false # Boolean flag

# Final verification settings
enable_verification: true

# Physical Dimensions (in micrometers)
physical_cell_height_um: 50.0
physical_cell_width_um: 10.0

# multiprograming grid configuration
grid_cols: 5
grid_rows: 2

# Scheduling and Routing Strategies
scheduling_strategy: "asap" # As Soon As Possible
routing_strategy: "maximalis_sort"
reuse: true
resyn: true
has_dependency: true
num_aods: 2
no_row1q_gates: False