[project]
name = "multiq"
version = "0.1"
description = "The description of the package"
authors = [
    {name = "FranciscoRomao", email = "francisco.romao@tum.de"},
    {name = "Dan Vonk", email = "dan@danvonk.com"},
]

dependencies = [
    "qiskit>=2.0.2",
    "matplotlib<4.0,>=3.0",
    "pylatexenc<3.0,>=2.0",
    "pandas==2.2.3",
    "networkx<4.0.0,>=3.4.2",
    "mqt-bench>=1.1.9",
    "zac@git+https://github.com/danvonk/ZAC.git",
    "pachinqo@git+https://github.com/positivetechnologylab/PachinQo",
    "pyyaml>=6.0.2",
    "mqt-qcec>=3.0.0"
]

requires-python = ">=3.12.0"
readme = "README.md"
license = {text = "MIT"}
keywords = ["quantum", "compilers"]

[tool.pdm]
distribution = false
