animation: false
aod_minimum_separation: 2
arch_padding: 0
cooling_rate: 0.9
dynamic_placement: true
enable_verification: true
entanglement_height: 40
entanglement_site_separation:
- 12
- 10
fidelity_1q_gate: 0.9991
fidelity_2q_gate: 0.9955
fidelity_atom_transfer: 0.999
final_temperature: 0.5
grid_cols: 14
grid_rows: 2
has_dependency: true
initial_temperature: 10
l2: false
layer_split_window: 10
max_iterations: 1000
max_iterations_per_temp: 3
multiq_check: false
no_row1q_gates: false
num_aods: 1
perf_weight: 0.4
perf_weight_selector: 0
physical_cell_height_um: 95.0
physical_cell_width_um: 6
qpu_height: 155
qpu_width: 230
r1q_time: 52
results_dir: results/multiq
resyn: true
reuse: true
routing_strategy: maximalis_sort
scheduling_strategy: asap
selection_algorithm: sa
selector_algo: fifo
storage_site_separation:
- 3
- 3
storage_zone_cols: null
storage_zone_rows: null
time_1qGate: 52
time_1q_gate: 52
time_atom_transfer: 15
time_coherence: 1.5e6
time_rydberg: 0.36
tmp_arch_file: config/zac/tmp_architecture.json
trivial_placement: false
use_window: true
util_weight: 0
util_weight_selector: 1
window_size: 1000
zone_centering:
- 0
- 1
zone_separation: 10
